// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'2647cdb54890f93ff4ca734dbc54c656f05c6d4394f5f1f611a4b33229a2e749'>;
export type ExecutionHash =
  ExecutionHashBase<'f4de0efdf5b8533a4f7151bda857b943258632c9dc0ca5b9be4457e5e4c6acac'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly AcademicYear: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly yearName: CodecTypes['pg/text@1']['output'];
      readonly startDate: CodecTypes['pg/date-string@1']['output'];
      readonly endDate: CodecTypes['pg/date-string@1']['output'];
      readonly teacherId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Activity: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly evaluationId: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly weight: CodecTypes['pg/float8@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Enrollment: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly studentId: CodecTypes['pg/uuid@1']['output'];
      readonly subjectId: CodecTypes['pg/uuid@1']['output'];
      readonly academicYearId: CodecTypes['pg/uuid@1']['output'];
      readonly registrationDate: CodecTypes['pg/date-string@1']['output'];
    };
    readonly Evaluation: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly periodId: CodecTypes['pg/uuid@1']['output'];
      readonly type: 'NOTE_1' | 'NOTE_2' | 'EXAM';
      readonly weight: CodecTypes['pg/float8@1']['output'];
      readonly activityOrder: CodecTypes['pg/int4@1']['output'];
    };
    readonly Grade: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly enrollmentId: CodecTypes['pg/uuid@1']['output'];
      readonly activityId: CodecTypes['pg/uuid@1']['output'] | null;
      readonly subActivityId: CodecTypes['pg/uuid@1']['output'] | null;
      readonly gradeValue: Numeric<5, 2>;
      readonly submissionDate: CodecTypes['pg/date-string@1']['output'] | null;
      readonly status: 'PENDING' | 'SUBMITTED' | 'GRADING';
    };
    readonly Period: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly academicYearId: CodecTypes['pg/uuid@1']['output'];
      readonly number: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly Student: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly dni: CodecTypes['pg/text@1']['output'];
      readonly firstName: CodecTypes['pg/text@1']['output'];
      readonly lastName1: CodecTypes['pg/text@1']['output'];
      readonly lastName2: CodecTypes['pg/text@1']['output'] | null;
      readonly birthDate: CodecTypes['pg/date-string@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
    };
    readonly SubActivity: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly activityId: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly weight: CodecTypes['pg/float8@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Subject: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly code: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Teacher: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly AcademicYear: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly yearName: CodecTypes['pg/text@1']['input'];
      readonly startDate: CodecTypes['pg/date-string@1']['input'];
      readonly endDate: CodecTypes['pg/date-string@1']['input'];
      readonly teacherId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Activity: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly evaluationId: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly weight: CodecTypes['pg/float8@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Enrollment: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly studentId: CodecTypes['pg/uuid@1']['input'];
      readonly subjectId: CodecTypes['pg/uuid@1']['input'];
      readonly academicYearId: CodecTypes['pg/uuid@1']['input'];
      readonly registrationDate: CodecTypes['pg/date-string@1']['input'];
    };
    readonly Evaluation: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly periodId: CodecTypes['pg/uuid@1']['input'];
      readonly type: 'NOTE_1' | 'NOTE_2' | 'EXAM';
      readonly weight: CodecTypes['pg/float8@1']['input'];
      readonly activityOrder: CodecTypes['pg/int4@1']['input'];
    };
    readonly Grade: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly enrollmentId: CodecTypes['pg/uuid@1']['input'];
      readonly activityId: CodecTypes['pg/uuid@1']['input'] | null;
      readonly subActivityId: CodecTypes['pg/uuid@1']['input'] | null;
      readonly gradeValue: CodecTypes['pg/numeric@1']['input'];
      readonly submissionDate: CodecTypes['pg/date-string@1']['input'] | null;
      readonly status: 'PENDING' | 'SUBMITTED' | 'GRADING';
    };
    readonly Period: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly academicYearId: CodecTypes['pg/uuid@1']['input'];
      readonly number: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly Student: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly dni: CodecTypes['pg/text@1']['input'];
      readonly firstName: CodecTypes['pg/text@1']['input'];
      readonly lastName1: CodecTypes['pg/text@1']['input'];
      readonly lastName2: CodecTypes['pg/text@1']['input'] | null;
      readonly birthDate: CodecTypes['pg/date-string@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
    };
    readonly SubActivity: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly activityId: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly weight: CodecTypes['pg/float8@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Subject: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly code: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Teacher: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly academic_years: {
      readonly endDate: CodecTypes['pg/date-string@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly startDate: CodecTypes['pg/date-string@1']['output'];
      readonly teacherId: CodecTypes['pg/uuid@1']['output'];
      readonly yearName: CodecTypes['pg/text@1']['output'];
    };
    readonly activities: {
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly evaluationId: CodecTypes['pg/uuid@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly weight: CodecTypes['pg/float8@1']['output'];
    };
    readonly enrollments: {
      readonly academicYearId: CodecTypes['pg/uuid@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly registrationDate: CodecTypes['pg/date-string@1']['output'];
      readonly studentId: CodecTypes['pg/uuid@1']['output'];
      readonly subjectId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly evaluations: {
      readonly activityOrder: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly periodId: CodecTypes['pg/uuid@1']['output'];
      readonly type: 'NOTE_1' | 'NOTE_2' | 'EXAM';
      readonly weight: CodecTypes['pg/float8@1']['output'];
    };
    readonly grades: {
      readonly activityId: CodecTypes['pg/uuid@1']['output'] | null;
      readonly enrollmentId: CodecTypes['pg/uuid@1']['output'];
      readonly gradeValue: Numeric<5, 2>;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly status: 'PENDING' | 'SUBMITTED' | 'GRADING';
      readonly subActivityId: CodecTypes['pg/uuid@1']['output'] | null;
      readonly submissionDate: CodecTypes['pg/date-string@1']['output'] | null;
    };
    readonly periods: {
      readonly academicYearId: CodecTypes['pg/uuid@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly number: CodecTypes['pg/int4@1']['output'];
    };
    readonly students: {
      readonly birthDate: CodecTypes['pg/date-string@1']['output'];
      readonly dni: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly firstName: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly lastName1: CodecTypes['pg/text@1']['output'];
      readonly lastName2: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly sub_activities: {
      readonly activityId: CodecTypes['pg/uuid@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly weight: CodecTypes['pg/float8@1']['output'];
    };
    readonly subjects: {
      readonly code: CodecTypes['pg/text@1']['output'];
      readonly description: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly teachers: {
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly academic_years: {
      readonly endDate: CodecTypes['pg/date-string@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly startDate: CodecTypes['pg/date-string@1']['input'];
      readonly teacherId: CodecTypes['pg/uuid@1']['input'];
      readonly yearName: CodecTypes['pg/text@1']['input'];
    };
    readonly activities: {
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly evaluationId: CodecTypes['pg/uuid@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly weight: CodecTypes['pg/float8@1']['input'];
    };
    readonly enrollments: {
      readonly academicYearId: CodecTypes['pg/uuid@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly registrationDate: CodecTypes['pg/date-string@1']['input'];
      readonly studentId: CodecTypes['pg/uuid@1']['input'];
      readonly subjectId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly evaluations: {
      readonly activityOrder: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly periodId: CodecTypes['pg/uuid@1']['input'];
      readonly type: 'NOTE_1' | 'NOTE_2' | 'EXAM';
      readonly weight: CodecTypes['pg/float8@1']['input'];
    };
    readonly grades: {
      readonly activityId: CodecTypes['pg/uuid@1']['input'] | null;
      readonly enrollmentId: CodecTypes['pg/uuid@1']['input'];
      readonly gradeValue: CodecTypes['pg/numeric@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly status: 'PENDING' | 'SUBMITTED' | 'GRADING';
      readonly subActivityId: CodecTypes['pg/uuid@1']['input'] | null;
      readonly submissionDate: CodecTypes['pg/date-string@1']['input'] | null;
    };
    readonly periods: {
      readonly academicYearId: CodecTypes['pg/uuid@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly number: CodecTypes['pg/int4@1']['input'];
    };
    readonly students: {
      readonly birthDate: CodecTypes['pg/date-string@1']['input'];
      readonly dni: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly firstName: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly lastName1: CodecTypes['pg/text@1']['input'];
      readonly lastName2: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly sub_activities: {
      readonly activityId: CodecTypes['pg/uuid@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly weight: CodecTypes['pg/float8@1']['input'];
    };
    readonly subjects: {
      readonly code: CodecTypes['pg/text@1']['input'];
      readonly description: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly teachers: {
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Teacher = {
    id: CodecTypes['pg/uuid@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    academicYears: public_AcademicYear[];
    readonly [RelationKeys]?: 'academicYears';
  };
  export type public_AcademicYear = {
    id: CodecTypes['pg/uuid@1']['output'];
    yearName: CodecTypes['pg/text@1']['output'];
    startDate: CodecTypes['pg/date-string@1']['output'];
    endDate: CodecTypes['pg/date-string@1']['output'];
    teacherId: CodecTypes['pg/uuid@1']['output'];
    enrollments: public_Enrollment[];
    periods: public_Period[];
    teacher: public_Teacher;
    readonly [RelationKeys]?: 'enrollments' | 'periods' | 'teacher';
  };
  export type public_Period = {
    id: CodecTypes['pg/uuid@1']['output'];
    academicYearId: CodecTypes['pg/uuid@1']['output'];
    number: CodecTypes['pg/int4@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    academicYear: public_AcademicYear;
    evaluations: public_Evaluation[];
    readonly [RelationKeys]?: 'academicYear' | 'evaluations';
  };
  export type public_Student = {
    id: CodecTypes['pg/uuid@1']['output'];
    dni: CodecTypes['pg/text@1']['output'];
    firstName: CodecTypes['pg/text@1']['output'];
    lastName1: CodecTypes['pg/text@1']['output'];
    lastName2: CodecTypes['pg/text@1']['output'] | null;
    birthDate: CodecTypes['pg/date-string@1']['output'];
    email: CodecTypes['pg/text@1']['output'];
    enrollments: public_Enrollment[];
    readonly [RelationKeys]?: 'enrollments';
  };
  export type public_Subject = {
    id: CodecTypes['pg/uuid@1']['output'];
    code: CodecTypes['pg/text@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    description: CodecTypes['pg/text@1']['output'] | null;
    enrollments: public_Enrollment[];
    readonly [RelationKeys]?: 'enrollments';
  };
  export type public_Enrollment = {
    id: CodecTypes['pg/uuid@1']['output'];
    studentId: CodecTypes['pg/uuid@1']['output'];
    subjectId: CodecTypes['pg/uuid@1']['output'];
    academicYearId: CodecTypes['pg/uuid@1']['output'];
    registrationDate: CodecTypes['pg/date-string@1']['output'];
    academicYear: public_AcademicYear;
    grades: public_Grade[];
    student: public_Student;
    subject: public_Subject;
    readonly [RelationKeys]?: 'academicYear' | 'grades' | 'student' | 'subject';
  };
  export type public_Evaluation = {
    id: CodecTypes['pg/uuid@1']['output'];
    periodId: CodecTypes['pg/uuid@1']['output'];
    type: 'NOTE_1' | 'NOTE_2' | 'EXAM';
    weight: CodecTypes['pg/float8@1']['output'];
    activityOrder: CodecTypes['pg/int4@1']['output'];
    activities: public_Activity[];
    period: public_Period;
    readonly [RelationKeys]?: 'activities' | 'period';
  };
  export type public_Activity = {
    id: CodecTypes['pg/uuid@1']['output'];
    evaluationId: CodecTypes['pg/uuid@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    weight: CodecTypes['pg/float8@1']['output'];
    description: CodecTypes['pg/text@1']['output'] | null;
    evaluation: public_Evaluation;
    grades: public_Grade[];
    subActivities: public_SubActivity[];
    readonly [RelationKeys]?: 'evaluation' | 'grades' | 'subActivities';
  };
  export type public_SubActivity = {
    id: CodecTypes['pg/uuid@1']['output'];
    activityId: CodecTypes['pg/uuid@1']['output'];
    name: CodecTypes['pg/text@1']['output'];
    weight: CodecTypes['pg/float8@1']['output'];
    description: CodecTypes['pg/text@1']['output'] | null;
    activity: public_Activity;
    grades: public_Grade[];
    readonly [RelationKeys]?: 'activity' | 'grades';
  };
  export type public_Grade = {
    id: CodecTypes['pg/uuid@1']['output'];
    enrollmentId: CodecTypes['pg/uuid@1']['output'];
    activityId: CodecTypes['pg/uuid@1']['output'] | null;
    subActivityId: CodecTypes['pg/uuid@1']['output'] | null;
    gradeValue: Numeric<5, 2>;
    submissionDate: CodecTypes['pg/date-string@1']['output'] | null;
    status: 'PENDING' | 'SUBMITTED' | 'GRADING';
    activity: public_Activity | null;
    enrollment: public_Enrollment;
    subActivity: public_SubActivity | null;
    readonly [RelationKeys]?: 'activity' | 'enrollment' | 'subActivity';
  };
}

export declare const models: {
  public: {
    Teacher: Models.public_Teacher;
    AcademicYear: Models.public_AcademicYear;
    Period: Models.public_Period;
    Student: Models.public_Student;
    Subject: Models.public_Subject;
    Enrollment: Models.public_Enrollment;
    Evaluation: Models.public_Evaluation;
    Activity: Models.public_Activity;
    SubActivity: Models.public_SubActivity;
    Grade: Models.public_Grade;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly academic_years: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly yearName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly startDate: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly endDate: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly teacherId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['yearName'] }];
              indexes: readonly [
                {
                  readonly name: 'academic_years_teacherId_idx_bc266660';
                  readonly prefix: 'academic_years_teacherId_idx';
                  readonly columns: readonly ['teacherId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'academic_years';
                    readonly columns: readonly ['teacherId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'teachers';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly activities: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly evaluationId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly weight: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/float8@1', 100>;
                  };
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['evaluationId', 'name'] }];
              indexes: readonly [
                {
                  readonly name: 'activities_evaluationId_idx_668799a5';
                  readonly prefix: 'activities_evaluationId_idx';
                  readonly columns: readonly ['evaluationId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'activities';
                    readonly columns: readonly ['evaluationId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'evaluations';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly enrollments: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly studentId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly subjectId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly academicYearId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly registrationDate: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['studentId', 'subjectId', 'academicYearId'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'enrollments_studentId_idx_bf255322';
                  readonly prefix: 'enrollments_studentId_idx';
                  readonly columns: readonly ['studentId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'enrollments_subjectId_idx_84df2a1d';
                  readonly prefix: 'enrollments_subjectId_idx';
                  readonly columns: readonly ['subjectId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'enrollments_academicYearId_idx_420494e0';
                  readonly prefix: 'enrollments_academicYearId_idx';
                  readonly columns: readonly ['academicYearId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'enrollments';
                    readonly columns: readonly ['studentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'students';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'enrollments';
                    readonly columns: readonly ['subjectId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'subjects';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'enrollments';
                    readonly columns: readonly ['academicYearId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'academic_years';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly evaluations: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly periodId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly weight: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/float8@1', 35>;
                  };
                };
                readonly activityOrder: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['periodId', 'type'] }];
              indexes: readonly [
                {
                  readonly name: 'evaluations_periodId_type_idx_e86eefea';
                  readonly prefix: 'evaluations_periodId_type_idx';
                  readonly columns: readonly ['periodId', 'type'];
                  readonly unique: false;
                },
                {
                  readonly name: 'evaluations_periodId_idx_f0176b8a';
                  readonly prefix: 'evaluations_periodId_idx';
                  readonly columns: readonly ['periodId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'evaluations';
                    readonly columns: readonly ['periodId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'periods';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly grades: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly enrollmentId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly activityId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: true;
                };
                readonly subActivityId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: true;
                };
                readonly gradeValue: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 5; readonly scale: 2 };
                };
                readonly submissionDate: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['enrollmentId', 'activityId'] },
                { readonly columns: readonly ['enrollmentId', 'subActivityId'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'grades_enrollmentId_idx_ee5e79c5';
                  readonly prefix: 'grades_enrollmentId_idx';
                  readonly columns: readonly ['enrollmentId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'grades_activityId_idx_bf2a659e';
                  readonly prefix: 'grades_activityId_idx';
                  readonly columns: readonly ['activityId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'grades_subActivityId_idx_a433c5b7';
                  readonly prefix: 'grades_subActivityId_idx';
                  readonly columns: readonly ['subActivityId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'grades';
                    readonly columns: readonly ['enrollmentId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'enrollments';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'grades';
                    readonly columns: readonly ['activityId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'activities';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'grades';
                    readonly columns: readonly ['subActivityId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'sub_activities';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly periods: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly academicYearId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly number: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['academicYearId', 'number'] }];
              indexes: readonly [
                {
                  readonly name: 'periods_academicYearId_idx_420494e0';
                  readonly prefix: 'periods_academicYearId_idx';
                  readonly columns: readonly ['academicYearId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'periods';
                    readonly columns: readonly ['academicYearId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'academic_years';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly students: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly dni: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly firstName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly lastName1: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly lastName2: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly birthDate: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['dni'] },
                { readonly columns: readonly ['email'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly sub_activities: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly activityId: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly weight: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['activityId', 'name'] }];
              indexes: readonly [
                {
                  readonly name: 'sub_activities_activityId_idx_bf2a659e';
                  readonly prefix: 'sub_activities_activityId_idx';
                  readonly columns: readonly ['activityId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'sub_activities';
                    readonly columns: readonly ['activityId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'activities';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly subjects: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly code: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly description: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['code'] }];
              indexes: readonly [
                {
                  readonly name: 'subjects_code_idx_8e43b86b';
                  readonly prefix: 'subjects_code_idx';
                  readonly columns: readonly ['code'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly teachers: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly EvaluationType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['NOTE_1', 'NOTE_2', 'EXAM'];
            };
            readonly GradeStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDING', 'SUBMITTED', 'GRADING'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly teachers: { readonly namespace: 'public' & NamespaceId; readonly model: 'Teacher' };
    readonly academic_years: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'AcademicYear';
    };
    readonly periods: { readonly namespace: 'public' & NamespaceId; readonly model: 'Period' };
    readonly students: { readonly namespace: 'public' & NamespaceId; readonly model: 'Student' };
    readonly subjects: { readonly namespace: 'public' & NamespaceId; readonly model: 'Subject' };
    readonly enrollments: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Enrollment';
    };
    readonly evaluations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Evaluation';
    };
    readonly activities: { readonly namespace: 'public' & NamespaceId; readonly model: 'Activity' };
    readonly sub_activities: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'SubActivity';
    };
    readonly grades: { readonly namespace: 'public' & NamespaceId; readonly model: 'Grade' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly AcademicYear: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly yearName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly startDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly endDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly teacherId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly enrollments: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Enrollment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['academicYearId'];
                };
              };
              readonly periods: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Period';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['academicYearId'];
                };
              };
              readonly teacher: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Teacher';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['teacherId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'academic_years';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly yearName: { readonly column: 'yearName' };
                readonly startDate: { readonly column: 'startDate' };
                readonly endDate: { readonly column: 'endDate' };
                readonly teacherId: { readonly column: 'teacherId' };
              };
            };
          };
          readonly Activity: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly evaluationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly weight: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly evaluation: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Evaluation';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['evaluationId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly grades: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Grade';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['activityId'];
                };
              };
              readonly subActivities: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SubActivity';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['activityId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'activities';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly evaluationId: { readonly column: 'evaluationId' };
                readonly name: { readonly column: 'name' };
                readonly weight: { readonly column: 'weight' };
                readonly description: { readonly column: 'description' };
              };
            };
          };
          readonly Enrollment: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly studentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly subjectId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly academicYearId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly registrationDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
            };
            readonly relations: {
              readonly academicYear: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AcademicYear';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['academicYearId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly grades: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Grade';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['enrollmentId'];
                };
              };
              readonly student: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Student';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['studentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly subject: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Subject';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['subjectId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'enrollments';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly studentId: { readonly column: 'studentId' };
                readonly subjectId: { readonly column: 'subjectId' };
                readonly academicYearId: { readonly column: 'academicYearId' };
                readonly registrationDate: { readonly column: 'registrationDate' };
              };
            };
          };
          readonly Evaluation: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly periodId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly weight: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly activityOrder: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly activities: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Activity';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['evaluationId'];
                };
              };
              readonly period: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Period';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['periodId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'evaluations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly periodId: { readonly column: 'periodId' };
                readonly type: { readonly column: 'type' };
                readonly weight: { readonly column: 'weight' };
                readonly activityOrder: { readonly column: 'activityOrder' };
              };
            };
          };
          readonly Grade: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly enrollmentId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly activityId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly subActivityId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly gradeValue: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/numeric@1';
                  readonly typeParams: { readonly precision: 5; readonly scale: 2 };
                };
              };
              readonly submissionDate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly activity: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Activity';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['activityId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly enrollment: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Enrollment';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['enrollmentId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly subActivity: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'SubActivity';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['subActivityId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'grades';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly enrollmentId: { readonly column: 'enrollmentId' };
                readonly activityId: { readonly column: 'activityId' };
                readonly subActivityId: { readonly column: 'subActivityId' };
                readonly gradeValue: { readonly column: 'gradeValue' };
                readonly submissionDate: { readonly column: 'submissionDate' };
                readonly status: { readonly column: 'status' };
              };
            };
          };
          readonly Period: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly academicYearId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly number: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly academicYear: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AcademicYear';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['academicYearId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly evaluations: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Evaluation';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['periodId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'periods';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly academicYearId: { readonly column: 'academicYearId' };
                readonly number: { readonly column: 'number' };
                readonly name: { readonly column: 'name' };
              };
            };
          };
          readonly Student: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly dni: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly firstName: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastName1: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastName2: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly birthDate: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly enrollments: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Enrollment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['studentId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'students';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly dni: { readonly column: 'dni' };
                readonly firstName: { readonly column: 'firstName' };
                readonly lastName1: { readonly column: 'lastName1' };
                readonly lastName2: { readonly column: 'lastName2' };
                readonly birthDate: { readonly column: 'birthDate' };
                readonly email: { readonly column: 'email' };
              };
            };
          };
          readonly SubActivity: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly activityId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly weight: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly activity: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Activity';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['activityId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly grades: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Grade';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['subActivityId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'sub_activities';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly activityId: { readonly column: 'activityId' };
                readonly name: { readonly column: 'name' };
                readonly weight: { readonly column: 'weight' };
                readonly description: { readonly column: 'description' };
              };
            };
          };
          readonly Subject: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly code: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly enrollments: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Enrollment';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['subjectId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'subjects';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly code: { readonly column: 'code' };
                readonly name: { readonly column: 'name' };
                readonly description: { readonly column: 'description' };
              };
            };
          };
          readonly Teacher: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly academicYears: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AcademicYear';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['teacherId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'teachers';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly email: { readonly column: 'email' };
              };
            };
          };
        };
        readonly enum: {
          readonly GradeStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'SUBMITTED'; readonly value: 'SUBMITTED' },
              { readonly name: 'GRADING'; readonly value: 'GRADING' },
            ];
          };
          readonly EvaluationType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'NOTE_1'; readonly value: 'NOTE_1' },
              { readonly name: 'NOTE_2'; readonly value: 'NOTE_2' },
              { readonly name: 'EXAM'; readonly value: 'EXAM' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'academic_years';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'activities';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'enrollments';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'evaluations';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'grades';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'periods';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'students';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'sub_activities';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'subjects';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'teachers';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
